### ISSUE TITLE
Certains enregistrements n'appaissent pas dans l'import

### ISSUE THREAD

**Issue by vinyll** [betagouv/eac-api#8]
Le théâtre Gérard Philipe (93) n'apparaît pas dans les résultats, alors qu'il est dans la base que je vous ai transmise

**Comment by rap2hpoutre** [comment]
Selon moi c'est bon, extrait de mon message à Loup Wolff : 

> rap2h [< 1 minute ago]
En choisissant le collège Diderot à Aubervilliers (93) et en saisissant “Gérard Philipe” dans la recherche j’obtiens en premier le CDN. Donc ça me semble bon (le problème était peut-être dû au classement par distance qui était pété, ou à la base de donnée qui n’était pas tout à fait à jour). À ta dispo si ça ne te va pas :slightly_smiling_face: !

Donc je ne sais pas ce qui a pu provoquer ce problème, mais en tout cas, ça ressort (bien entendu, pas en premier si un autre établissement est plus près).
